package net.suncaper.projecttracking.domain;

public class JointCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_joint_company.id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_joint_company.company_name
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_joint_company.compnay_id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private String compnayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_joint_company.id
     *
     * @return the value of pt_joint_company.id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_joint_company.id
     *
     * @param id the value for pt_joint_company.id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_joint_company.company_name
     *
     * @return the value of pt_joint_company.company_name
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_joint_company.company_name
     *
     * @param companyName the value for pt_joint_company.company_name
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_joint_company.compnay_id
     *
     * @return the value of pt_joint_company.compnay_id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public String getCompnayId() {
        return compnayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_joint_company.compnay_id
     *
     * @param compnayId the value for pt_joint_company.compnay_id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setCompnayId(String compnayId) {
        this.compnayId = compnayId == null ? null : compnayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JointCompany other = (JointCompany) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getCompnayId() == null ? other.getCompnayId() == null : this.getCompnayId().equals(other.getCompnayId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getCompnayId() == null) ? 0 : getCompnayId().hashCode());
        return result;
    }
}