package net.suncaper.projecttracking.domain;

public class ProjectLeaderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_leader.user_id
     *
     * @mbg.generated Fri Dec 20 14:24:46 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_leader.project_id
     *
     * @mbg.generated Fri Dec 20 14:24:46 CST 2019
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_leader.user_id
     *
     * @return the value of project_leader.user_id
     *
     * @mbg.generated Fri Dec 20 14:24:46 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_leader.user_id
     *
     * @param userId the value for project_leader.user_id
     *
     * @mbg.generated Fri Dec 20 14:24:46 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_leader.project_id
     *
     * @return the value of project_leader.project_id
     *
     * @mbg.generated Fri Dec 20 14:24:46 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_leader.project_id
     *
     * @param projectId the value for project_leader.project_id
     *
     * @mbg.generated Fri Dec 20 14:24:46 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}