package net.suncaper.projecttracking.domain;

public class SysDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_sys_dic.id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_sys_dic.type
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_sys_dic.code
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_sys_dic.value
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_sys_dic.fixed
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    private Boolean fixed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_sys_dic.id
     *
     * @return the value of pt_sys_dic.id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_sys_dic.id
     *
     * @param id the value for pt_sys_dic.id
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_sys_dic.type
     *
     * @return the value of pt_sys_dic.type
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_sys_dic.type
     *
     * @param type the value for pt_sys_dic.type
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_sys_dic.code
     *
     * @return the value of pt_sys_dic.code
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_sys_dic.code
     *
     * @param code the value for pt_sys_dic.code
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_sys_dic.value
     *
     * @return the value of pt_sys_dic.value
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_sys_dic.value
     *
     * @param value the value for pt_sys_dic.value
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_sys_dic.fixed
     *
     * @return the value of pt_sys_dic.fixed
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public Boolean getFixed() {
        return fixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_sys_dic.fixed
     *
     * @param fixed the value for pt_sys_dic.fixed
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    public void setFixed(Boolean fixed) {
        this.fixed = fixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_sys_dic
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysDict other = (SysDict) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getFixed() == null ? other.getFixed() == null : this.getFixed().equals(other.getFixed()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_sys_dic
     *
     * @mbg.generated Tue Dec 24 15:04:23 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getFixed() == null) ? 0 : getFixed().hashCode());
        return result;
    }
}